"""Report export generators for the local workbench.

Produces JSON, CSV, and PyMOL-script exports from the combined V3 analysis
payload (V2 report + structural context + causal graph + literature).
All content is derived from the same data the page renders, so exports and
the on-screen report stay consistent.
"""

from __future__ import annotations

import csv
import io
import json


def _flat_evidence_rows(payload: dict) -> list[dict]:
    """Flatten physical evidence, mechanisms, and hypotheses into table rows."""
    v2 = payload.get("v2_report") or payload
    rows: list[dict] = []

    def push(items, kind):
        for item in items or []:
            measurement = item.get("measurement") or {}
            rows.append(
                {
                    "kind": kind,
                    "id": item.get("id", ""),
                    "title": item.get("title")
                    or item.get("objective")
                    or item.get("evidence_type")
                    or item.get("mechanism_type", ""),
                    "status": item.get("status", ""),
                    "measurement_name": measurement.get("name", ""),
                    "value": measurement.get("value", ""),
                    "unit": measurement.get("unit", ""),
                    "confidence": item.get("confidence", ""),
                    "qualitative_confidence": item.get("qualitative_confidence", ""),
                    "calibration_status": item.get("calibration_status", ""),
                    "description": (item.get("description") or item.get("reason") or "")[:400],
                    "supports": ";".join(item.get("supports") or []),
                    "contradicts": ";".join(item.get("contradicts") or []),
                }
            )

    push(v2.get("physical_evidence"), "physical_evidence")
    push(v2.get("structural_mechanisms"), "structural_mechanism")
    push(v2.get("functional_hypotheses"), "functional_hypothesis")
    push(v2.get("missing_evidence"), "missing_evidence")
    push((v2.get("validation_plan") or {}).get("steps"), "validation_step")
    return rows


def report_to_json(payload: dict) -> str:
    """Serialize the combined analysis payload as indented JSON."""
    return json.dumps(payload, ensure_ascii=False, indent=2, default=str)


def report_to_csv(payload: dict) -> str:
    """Serialize evidence/mechanism rows as CSV text."""
    rows = _flat_evidence_rows(payload)
    buffer = io.StringIO()
    if not rows:
        buffer.write("# no rows\n")
        return buffer.getvalue()
    fieldnames = list(rows[0].keys())
    writer = csv.DictWriter(buffer, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)
    return buffer.getvalue()


def report_to_pymol(payload: dict) -> str:
    """Generate a PyMOL (.pml) session script for the analyzed case.

    The script highlights the mutation site and ligand in both structures.
    Structure paths are the local paths known to the server; adjust them if
    the script is run on another machine.
    """
    v2 = payload.get("v2_report") or payload
    request = v2.get("request") or {}
    mutation = request.get("mutation") or {}
    ligand = request.get("ligand") or {}
    structure = request.get("structure") or {}
    mutant_structure = request.get("mutant_structure") or {}
    v3_ctx = payload.get("v3_context") or {}

    chain = mutation.get("chain") or "A"
    resnum = mutation.get("residue_number", "")
    notation = mutation.get("notation", "")
    ligand_id = (ligand.get("identifier") or "LIG").upper()
    wt_path = structure.get("path", "")
    mutant_path = mutant_structure.get("path", "")
    neighborhood = [n.get("label", "") for n in (v3_ctx.get("neighborhood_4a") or [])]

    lines = [
        "# PSF-Reasoner PyMOL session script",
        f"# Mutation: {notation} (chain {chain}), Ligand: {ligand_id}",
        "# Generated by the local workbench export.  Adjust structure paths",
        "# if you open this script on a different machine.",
        "",
        "# -- Load structures ------------------------------------------------",
    ]
    if wt_path:
        lines.append(f"load {wt_path}, reference")
        lines.append("hide everything, reference")
        lines.append("show cartoon, reference")
    if mutant_path:
        lines.append(f"load {mutant_path}, mutant")
        lines.append("hide everything, mutant")
        lines.append("show cartoon, mutant")
        lines.append("color slate, mutant and not (resn " + ligand_id + ")")

    lines += [
        "",
        "# -- Mutation site ---------------------------------------------------",
    ]
    if resnum != "":
        lines.append(f"select mutation_site, chain {chain} and resi {resnum}")
        lines.append("show sticks, mutation_site")
        lines.append("color tv_red, mutation_site")
        lines.append(f"select mutation_site_mutant, mutant and chain {chain} and resi {resnum}")
        lines.append("show sticks, mutation_site_mutant")
        lines.append("color tv_red, mutation_site_mutant")

    lines += [
        "",
        "# -- Ligand ----------------------------------------------------------",
        f"select ligand_sel, resn {ligand_id}",
        "show sticks, ligand_sel",
        "color tv_blue, ligand_sel",
        "",
        "# -- 4 Angstrom neighborhood (from structural context) ----------------",
    ]
    if neighborhood:
        neighbor_sel = " or ".join(
            f"(chain {chain} and resi {_resi_from_label(label, resnum)})"
            for label in neighborhood
            if _resi_from_label(label, resnum) is not None
        )
        if neighbor_sel:
            lines.append(f"select neighborhood_4a, {neighbor_sel}")
            lines.append("show sticks, neighborhood_4a")
            lines.append("color yellow, neighborhood_4a")
    else:
        lines.append("# no neighborhood data in this analysis")

    lines += [
        "",
        "# -- View ------------------------------------------------------------",
        "zoom mutation_site or ligand_sel",
        "set bg_color, white",
        "set stick_radius, 0.2",
        "",
        "# Run 'ray' for a rendered image, or 'png session.png' to save one.",
    ]
    return "\n".join(lines) + "\n"


def _resi_from_label(label: str, mutation_resnum) -> str | None:
    """Extract the residue number from a 'chain:XXXnum' label.

    Returns None when the label belongs to the mutation site itself (so the
    neighborhood selection does not duplicate the mutation-site selection).
    """
    try:
        rest = label.split(":", 1)[1]
    except IndexError:
        return None
    digits = ""
    for ch in rest:
        if ch.isdigit():
            digits += ch
        elif digits:
            break
        if len(digits) > 4:
            return None
    if not digits:
        return None
    if str(mutation_resnum) and digits == str(mutation_resnum):
        return None
    return digits
